### ISSUE TITLE
2.2.3节翻译问题

### ISSUE THREAD

**Issue by Aurora-N** [csfive/composing-programs-zh#120]
[2.2.3节](https://composingprograms.netlify.app/2/2#_2-2-3-%E6%8A%BD%E8%B1%A1%E9%9A%9C%E7%A2%8D)表格下面第二段的第一句话：每当程序的一部分可以使用更高级别的函数**而不是**使用较低级别的函数时，就会违反抽象障碍。

读起来有些歧义，应该为：每当程序中可以使用更高级别函数的一部分使用了较低级别的函数时，就会违反抽象屏障。

或者改为：每当程序的一部分可以使用更高级别的函数**却**使用了较低级别的函数时，就会违反抽象障碍。

[原文](https://www.composingprograms.com/pages/22-data-abstraction.html#abstraction-barriers)：An abstraction barrier violation occurs whenever a part of the program that can use a higher level function instead uses a function in a lower level.

**Comment by Aurora-N** [comment]
此外，**抽象障碍**改为**抽象屏障**也许会更为恰当。

**Comment by mancuoj** [comment]
确实，我也觉得抽象屏障更好，另外，这种好意见可以不开 issue 直接 PR 我都会接受 ❤️
