### ISSUE TITLE
2.3 及 2.4 节翻译质量问题，需要贡献

### ISSUE THREAD

**Issue by mancuoj** [csfive/composing-programs-zh#126]
注意到 2.3 与 2.4 节翻译质量低，加之格式不符合标准，之前合并属实不该，现征集小伙伴重新翻译

**Comment by mancuoj** [comment]
> 大概要什么时候翻完，我有空可以弄一下，刚好前几天看了这两节还有点印象，是在原来基础上修正还是全部重新翻，感觉这两节概念多很抽象确实不太好翻。

一到两周内，最好是重新来过，因为我觉得在原有基础上review再修改的过程远比重新来过折磨，当然这看你的想法

**Comment by zyl1121** [comment]
> > 大概要什么时候翻完，我有空可以弄一下，刚好前几天看了这两节还有点印象，是在原来基础上修正还是全部重新翻，感觉这两节概念多很抽象确实不太好翻。
> 
> 一到两周内，最好是重新来过，因为我觉得在原有基础上review再修改的过程远比重新来过折磨，当然这看你的想法
好的，那我先把2.3翻了

**Comment by Joeljt** [comment]
认领一下 2.4，如果还需要的话~🙋‍♀️

**Comment by mancuoj** [comment]
> 认领一下 2.4，如果还需要的话~🙋‍♀️

可以的，欢迎贡献
