### ISSUE TITLE
请问可以制作成pdf文件吗？

### ISSUE THREAD

**Issue by shifang99** [csfive/composing-programs-zh#131]

**Comment by mancuoj** [comment]
markdown 文件都在仓库里了，网上 markdown 转 pdf 的方法还是挺多的，可以自己试试 💪

**Comment by tshemeng** [comment]
[COMPOSING PROGRAMS.pdf](https://github.com/user-attachments/files/16946140/COMPOSING.PROGRAMS.pdf)
@shifang99
