### ISSUE TITLE
建议在简介或者第一章中增加SICP的全称 Structure and Interpretation of Computer

### ISSUE THREAD

**Issue by shifang99** [csfive/composing-programs-zh#132]
建议修改为：
https://composingprograms.netlify.app/
这是一个翻译项目，原书为伯克利 CS61A 的配套教材 [Composing Programs](https://www.composingprograms.com/)，也是计算机一大圣经 [Structure and Interpretation of Computer, SICP](https://book.douban.com/subject/1148282/) 的 Python 版本。

https://composingprograms.netlify.app/1/1
长期以来，我们都使用 Harold Abelson、Gerald Jay Sussman 和 Julie Sussman 三人编写的经典教科书《计算机程序的构造与解释》即 SICP(Structure and Interpretation of Computer) 来教授这些基本思想，而本书大量借鉴了这本教科书。

**Comment by mancuoj** [comment]
我是尽可能简化了描述，超链接会解释一切
