### ISSUE TITLE
对“1.5.2 复合语句”中某个句子翻译的一点改进建议

### ISSUE THREAD

**Issue by shifang99** [csfive/composing-programs-zh#133]
这个中文翻译仓库极大得提高了学习效率。
我在阅读中发现有个句子稍欠通顺，查了原文对照之后，提出一点改进建议，希望能给这个仓库做一点点贡献。

- 英文原文

Compound statements typically span multiple lines and start with a one-line header ending in a colon, which identifies the type of statement.

- 原始翻译

复合语句通常跨越多行，以单行头部（header）开始，并以冒号结尾，冒号标识语句的类型。

- 改进建议

为了体现原文中的which从句，建议翻译成：
复合语句通常跨越多行，以单行头部（header）开始，并以冒号结尾，**_其中_** 冒号标识语句的类型。
或者
复合语句通常跨越多行，以单行头部（header）开始，并以 _**标识语句类型的冒号**_ 结尾。

**Comment by mancuoj** [comment]
感谢你的建议 ❤️ 如果你想让头像出现在贡献者列表，可以尝试着自己 PR 修改，因为都是文本内容，甚至可以直接在 GitHub 网页上进行修改后提交 PR，大概步骤就是点进具体文件，点击编辑按钮，修改对应地方，按提示提交修改（具体可能需要你搜索一下）。
