### ISSUE TITLE
针对专业名词的改进建议

### ISSUE THREAD

**Issue by shifang99** [csfive/composing-programs-zh#134]
改进建议：
（1）对专业名词增加中英文对照表；
例如：
赋值：assignment
语句：statement
表达式：expression

（2）文中第一次出现某个专业名词时，在中文后面的括号内附上英文全名，如果有缩写也把缩写附上。
对于这一条建议，仓库中的翻译大部分地方实现了这一建议，只是偶尔有些地方有遗漏。
例如：第一次提到“语句”时，没有附上 statement 这个英文名。
https://composingprograms.netlify.app/1/5
1.5.1 语句
到目前为止，我们虽然主要思考的是如何计算求解表达式，但我们已经见过了三种语句：赋值（assignment）、 def 和 return 语句。尽管这些 Python 代码都包含表达式作为它们的一部分，但它们本身并不是表达式。

**Comment by mancuoj** [comment]
这个确实，可能需要更多 PR 来进行修复
