### ISSUE TITLE
1.3 定义新的函数 Name Evaluation的翻译不准确

### ISSUE THREAD

**Issue by longguzzz** [csfive/composing-programs-zh#155]
Name Evaluation. A name evaluates to the value bound to that name in the earliest frame of the current environment in which that name is found.
被翻译成了“名称求解（Name Evaluation）：名称的计算结果为该名称所在环境中的最早的帧中与它绑定的值。”

推荐翻译：
名称求值，指的是：在环境寻找该名称，最早找到含有该名称的帧里边其绑定的值就是这个名称的计算结果。

in which that name is found这个限定性定语从句修饰的是the earliest frame，其实意思是，“在能找到这个名字的帧里边，最早找到的那个帧”。而不是“能找到这个名称的环境”里边的“最早的帧”。

**Comment by mancuoj** [comment]
PR Welcome，欢迎贡献自己修改 ~
