### ISSUE TITLE
1.3.7 关于decimal的翻译

### ISSUE THREAD

**Issue by lingchen0213** [csfive/composing-programs-zh#162]
> 对于除法，Python 提供了两个中缀运算符：/ 和 //。前者是常规除法，因此即使除数可以整除被除数，它也会产生浮点数或十进制值：

在这一段中，”它也会产生 浮点数 或十进制值” 的原文是 “so that it results in a floating point, or decimal value“，此处 ”decimal value“ 翻译成 ”十进制值“ 感觉不太方便初学者理解

参考[剑桥辞典](https://dictionary.cambridge.org/zhs/词典/英语-汉语-简体/decimal)给出的英汉释义
> DECIMAL翻译：十进位的, 小数; 十进小数

对于python初学者来说，“十进制值”的含义比较难以理解，且原文有floating point与decimal value有同义替换的意思，原版的中文翻译在文本上可能会带给读者一种“有可能生成浮点数，也有可能生成十进制值（另一种数值）”的偏差理解。

建议修改为：
>对于除法，Python 提供了两个中缀运算符：/ 和 //。前者是常规除法，因此即使除数可以整除被除数，它也会产生**浮点数（十进小数值）**：

非常感谢学长学姐们的贡献！！！辛苦啦！❤️

**Comment by mancuoj** [comment]
good catch, 感谢
