### ISSUE TITLE
⭐️ 共建计划

### ISSUE THREAD

**Issue by mancuoj** [csfive/composing-programs-zh#3]
翻译其实是一件非常适合开源新手的事情，你可以一边学习 CS61A 一边进行翻译，同时也可以熟悉开源流程，感受团队协作带来的乐趣。所以还是希望能有更多小伙伴参与进来，一起进步。

## Todos

第二章

- [ ] 2.9

第四章

- [ ] 4.5
- [ ] 4.7

## 如何参与

- 对于想参与的同学，可以直接回复本 issue 领取一个 Todo 即可
- 领取之后，fork 项目，翻译该节，提交 PR 即可，我会 review 之后合并
- 具体流程可以参考 #4 
- 不排斥占领坑位，不过还是希望尽量在一周之内完成翻译
- 在提交了有价值的 PR 后，我会拉你加入本组织
- ...

## 如何翻译

- 请参考第一章的翻译，以及 [中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines)
- 必要的英语概念需要在括号内标注，比如：高阶函数（higher-order function）
- Python Tutor 需要使用 iframe 嵌入，Scheme 语言暂时用链接代替
- 公式需要使用 LaTeX 插入
- 图片需要下载至 public 文件夹下
- ...

## 另外

开启计划后，陆陆续续也有些 PR，但翻译质量良莠不齐，我由于工作原因也不能大量投入时间在 Review 上。

于是有很多未经 Review 就被合并的 PR（大部分没有遵守 [中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines) 来做）。

所以如果有同学也想参与贡献但不想翻译大章，也可以通过 Review 来进行贡献，感谢！

**Comment by mancuoj** [comment]
领取 2-1

**Comment by Jinl-k** [comment]
太强了，感谢大佬，可惜我是个技术和英语都太菜了帮不上忙

**Comment by mancuoj** [comment]
> 太强了，感谢大佬，可惜我是个技术和英语都太菜了帮不上忙

翻译对你们有帮助就好😊我尽量早点翻完

**Comment by mancuoj** [comment]
领取 2-2

**Comment by Tr4cck** [comment]
领取 3-1

**Comment by fbchao** [comment]
领取 2-3

**Comment by anson-pro** [comment]
Hi, @mancuoj 我在考虑使用 ChatGPT 参与翻译，然后进行人工审查，你觉得这样的方案可以被接受吗？

**Comment by mancuoj** [comment]
> Hi, @mancuoj 我在考虑使用 ChatGPT 参与翻译，然后进行人工审查，你觉得这样的方案可以被接受吗？

可以的，只要后期人工再多复查几遍就行

**Comment by Tr4cck** [comment]
领取 3-2

**Comment by mancuoj** [comment]
> hey bro，我想知道2.4是翻译完的吗

没有打勾的都是没有翻译完的

**Comment by PirsLee** [comment]
> 领取4-1

领取4-2

**Comment by PirsLee** [comment]
对应的是哪一版的课程呢？

**Comment by Tr4cck** [comment]
关于[内嵌的 scheme interpreter](https://inst.eecs.berkeley.edu/~cs61a/fa14/assets/interpreter/scheme.html) 的实现标准是不是也需要明确一下

**Comment by mancuoj** [comment]
> 关于[内嵌的 scheme interpreter](https://inst.eecs.berkeley.edu/~cs61a/fa14/assets/interpreter/scheme.html) 的实现标准是不是也需要明确一下

啊，看上去有点麻烦，暂时先用链接代替吧，我之后看看有没有什么解决方式

**Comment by mancuoj** [comment]
> 关于[内嵌的 scheme interpreter](https://inst.eecs.berkeley.edu/~cs61a/fa14/assets/interpreter/scheme.html) 的实现标准是不是也需要明确一下

我找到了这个开源项目[klipse](https://github.com/viebel/klipse)可以嵌入，但实验了一下，限制有点太多了，不知道原书是怎么实现的，可能只能用链接了

**Comment by Jingsiradam** [comment]
感谢大佬！！

**Comment by spike014** [comment]
领取 [project01 Hog](https://inst.eecs.berkeley.edu/~cs61a/fa20/proj/hog/) 预计五一假期内完成。
预计放在第一章的最后，因为这部分是需要 1.1 - 1.6 的知识。
还是其他地方？ @mancuoj 问一下您的意见。

**Comment by mancuoj** [comment]
> 领取 [project01 Hog](https://inst.eecs.berkeley.edu/~cs61a/fa20/proj/hog/) #30 预计五一假期内完成。 预计放在第一章的最后，因为这部分是需要 1.2 - 1.6 的知识。 还是其他地方？ @mancuoj 问一下您的意见。

我觉得可以另开一个文件夹，然后放在导航栏中，类似，如果你不熟悉 vitepress，我可以帮你开一个 projects 文件夹

![image](https://user-images.githubusercontent.com/45707684/235109816-6d3a20df-d79b-4171-a3b7-32749cac4663.png)

**Comment by spike014** [comment]
> > 领取 [project01 Hog](https://inst.eecs.berkeley.edu/~cs61a/fa20/proj/hog/) #30 预计五一假期内完成。 预计放在第一章的最后，因为这部分是需要 1.2 - 1.6 的知识。 还是其他地方？ @mancuoj 问一下您的意见。
> 
> 我觉得可以另开一个文件夹，然后放在导航栏中，类似，如果你不熟悉 vitepress，我可以帮你开一个 projects 文件夹
> 
> ![image](https://user-images.githubusercontent.com/45707684/235109816-6d3a20df-d79b-4171-a3b7-32749cac4663.png)

好的，我还没用过 vitepress, 我不介意摸索一下，之后有问题我在这里反馈。

**Comment by Congwen-Wang** [comment]
领取2.3

**Comment by Congwen-Wang** [comment]
领取2.4

**Comment by CIQi6** [comment]
领取2.5

**Comment by HaiBooLang** [comment]
领取 2-6（大概两周内完成，希望可以:persevere:）

**Comment by Jesper-Y** [comment]
领取 2.6

**Comment by Jesper-Y** [comment]
领取 2.7

**Comment by lizzy-0323** [comment]
领取2.8

**Comment by Jesper-Y** [comment]
领取 2.9

**Comment by sumingfirst** [comment]
领取4.2，正好也在写这个课程，希望可以尽一份力

**Comment by Alan-Musk** [comment]
领取3.2

**Comment by sumingfirst** [comment]
你的邮件我受到非常感谢配合

**Comment by billycrapediem** [comment]
领取3.3

**Comment by Alan-Musk** [comment]
最近在赶进度,初学者,大概四五天结束,可以被顶掉

**Comment by Alan-Musk** [comment]
最近在赶进度,3.2可以被顶掉

**Comment by DuKle3** [comment]
領取4.2

**Comment by silver-ymz** [comment]
领取3.4

**Comment by Alan-Musk** [comment]
3.2 Done

**Comment by Alan-Musk** [comment]
领取 4.7

**Comment by billycrapediem** [comment]
领取4.6

**Comment by silver-ymz** [comment]
领取3.5

**Comment by sumingfirst** [comment]
领取4.8

**Comment by silver-ymz** [comment]
领取4.5

**Comment by mancuoj** [comment]
目前仅剩五小节还没更新~

**Comment by mancuoj** [comment]
转眼这个项目也有一年了，周期过长，我打算在一周内结束这个项目，还未完成翻译的小伙伴请尽快完成，如果没有时间的话，剩下的工作会由我进行收尾，再次感谢参与贡献的大家，你们的头像会永久保留在项目介绍中~
