### ISSUE TITLE
Considering that project after class is also important, have you considered translating or expanding the project section? 

### ISSUE THREAD

**Issue by spike014** [csfive/composing-programs-zh#30]
Considering that project after class is also important, have you considered translating or expanding the project section? 

project: http://composingprograms.com/projects.html

Thank you for your translation effort, and I am looking forward to your response.

**Comment by mancuoj** [comment]
当然，但是目前主要目标还是先把文章翻译完成。不过如果你自己想现在开始的话，欢迎 PR 👌

**Comment by spike014** [comment]
> 

Thanks for your such quick reply. I will work on it soon.

**Comment by spike014** [comment]
> > 
> 
> Thanks for your such quick reply. I will work on it soon.

I think those links of projecs from http://composingprograms.com/projects.html were expired. I noticed that the links were all about the fall semester of 2013. I recommend using update-friendly links like [cs61a/fa20/proj/hog](https://inst.eecs.berkeley.edu/~cs61a/fa20/proj/hog)
