### ISSUE TITLE
1.1.md

### ISSUE THREAD

**Issue by zjs2018** [csfive/composing-programs-zh#48]
最后，这个表达式

>>> {w for w in words if len(w) == 6 and w[::-1] in words}
{'redder', 'drawer', 'reward', 'diaper', 'repaid'}
是一个复合表达式，**它的计算结果是戏剧中所有正反拼写相同的单词的集合**。神秘符号 w[::-1] 表示枚举单词中的每个字母，其中 -1 代表反向枚举。当你在交互式会话中输入该表达式时，Python 会在下一行打印它的值。

解释器：复合表达式的求解需要以一个可预测的方式来精确解释代码的过程。实现这样的过程，用于计算复合表达式的程序就称为解释器。解释器的设计和实现是第三章的主题。

这个解释有点问题

**Comment by mancuoj** [comment]
图片没有挂，只不过 netlify 部署可能国内访问有限制，另外如果你有更好的翻译欢迎 PR 或给出修改方式（我没看出来哪里有问题，感谢！

**Comment by zjs2018** [comment]
Sry, 我理解有问题
